name: flutter_app
description: A Flutter application for audio transcription

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  flutter_sound: ^9.16.3
  http: ^1.2.2
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0  # Required for code generation
  flutter_gen: ^5.8.0  # Add this line if you're using flutter_gen

flutter:
  uses-material-design: true

  # Enable code generation for localizations
  generate: true

  assets:
    - audio_temp/  # Specify the directory for audio files if you have assets

